name=inpu("enter name:")
gender=("enter gender:")
branch=input("enter branch:")
college=("enter college:")
age=int(input("enter age:")
print("name: ", name)
print("gender: ",gender)
print("branch: ",branch)
print("college: ",college)
print("age: ",age)
